#Sensitive data which can be encoded as below
# type - Opaque means user defined secrets
apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
  labels:
    purpose: secret
    env: dev
type: Opaque
data:
  username: "YWRtaW4="
  password: "YWRtaW4zMjE="